import MarketInsightCard from "@/components/cards/MarketInsightCard";
import StatusBadge from "@/components/badges/StatusBadge";
import PageHeader from "@/components/layout/PageHeader";
import AiTransparencyNote from "@/components/research/AiTransparencyNote";
import MethodologyCallout from "@/components/research/MethodologyCallout";
import Link from "next/link";
import MarketRegimeBanner from "@/components/research/MarketRegimeBanner";
import StressInsightGrid from "@/components/research/StressInsightGrid";
import { getResearchDataset } from "@/lib/research";
import { buildPreviewStressReport, buildStressInsightCards } from "@/lib/quant/marketStress";
import { pct, pctPlain, num } from "@/lib/utils/format";

export const revalidate = 60 * 60;

export default async function AIMarketPage({ searchParams }: { searchParams?: { demo?: string } }) {
  const dataset = await getResearchDataset();
  const { factors, marketSummary, metadata } = dataset;
  // Clearly-labeled illustrative stress preview. Live by default; ?demo=stress
  // swaps in a representative risk-off regime (badged as non-live) so reviewers
  // can see the selloff surfaces when the real tape is calm.
  const previewMode = searchParams?.demo === "stress";
  const marketStress = previewMode ? buildPreviewStressReport(dataset.marketStress) : dataset.marketStress;
  const stressInsights = previewMode ? buildStressInsightCards(marketStress) : dataset.stressInsights;
  const above = factors.filter((factor) => factor.aboveSma200).length;
  const avgMom20 = factors.reduce((sum, factor) => sum + (factor.momentum20d ?? 0), 0) / Math.max(factors.length, 1);
  const avgVol = factors.reduce((sum, factor) => sum + (factor.volatility20d ?? 0), 0) / Math.max(factors.length, 1);

  // Data-derived regime notes (computed from the live factor snapshot — no static copy).
  const byMomentum = [...factors].filter((f) => f.momentum20d !== null).sort((a, b) => (b.momentum20d ?? 0) - (a.momentum20d ?? 0));
  const leader = byMomentum[0];
  const laggard = byMomentum[byMomentum.length - 1];
  const rsiExtreme = [...factors].filter((f) => f.rsi14 !== null).sort((a, b) => Math.abs((b.rsi14 ?? 50) - 50) - Math.abs((a.rsi14 ?? 50) - 50))[0];
  const breadthPct = factors.length > 0 ? above / factors.length : 0;
  const derivedNotes: Array<[string, string]> = [
    ["Trend breadth", `${above}/${factors.length} names above the 200-day average — ${breadthPct >= 0.7 ? "broad participation" : breadthPct <= 0.4 ? "narrow, defensive tape" : "mixed breadth"}.`],
    leader && leader.momentum20d !== null
      ? ["Momentum leader", `${leader.symbol} leads 20-day return at ${pct(leader.momentum20d)}${laggard && laggard.symbol !== leader.symbol && laggard.momentum20d !== null ? `; ${laggard.symbol} lags at ${pct(laggard.momentum20d)}` : ""}.`]
      : ["Momentum leader", "Insufficient momentum data in the current snapshot."],
    ["Volatility regime", `Average annualized 20-day volatility is ${pctPlain(avgVol)} — ${avgVol > 0.4 ? "elevated; tighten stops and sizing" : "controlled; continuation setups are viable"}.`],
    rsiExtreme && rsiExtreme.rsi14 !== null
      ? ["RSI watch", `${rsiExtreme.symbol} RSI14 at ${rsiExtreme.rsi14.toFixed(0)} is the watchlist extreme — ${rsiExtreme.rsi14 >= 70 ? "overbought" : rsiExtreme.rsi14 <= 30 ? "oversold" : "neutral"}.`]
      : ["RSI watch", "No RSI extreme in the current snapshot."],
  ];

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="L4 AI Market"
        title="AI Market Intelligence"
        subtitle="AI-written tape note layered on top of deterministic factor breadth, volatility, and trend metrics. When DEEPSEEK_API_KEY is set, the prose is generated by DeepSeek; otherwise it falls back to the template."
        actions={
          <div className="inline-flex rounded-full border border-line bg-white/[0.03] p-0.5 text-[11px]">
            <Link href="/ai-market" className={`rounded-full px-3 py-1.5 transition ${!previewMode ? "bg-white/[0.08] text-white" : "text-ink-soft hover:text-ink"}`}>Live regime</Link>
            <Link href="/ai-market?demo=stress" className={`rounded-full px-3 py-1.5 transition ${previewMode ? "bg-amber-400/15 text-amber-100" : "text-ink-soft hover:text-ink"}`}>Stress preview</Link>
          </div>
        }
      />

      {previewMode && (
        <div className="-mt-3 text-[11px] text-amber-100/80">
          Illustrative stressed regime — not live market data. Switch back to “Live regime” for the real tape.
        </div>
      )}

      <MarketRegimeBanner report={marketStress} />

      <AiTransparencyNote />

      <section>
        <div className="mb-3">
          <div className="panel-title">Market Intelligence — Selloff Conditions</div>
          <p className="mt-0.5 text-[11px] text-ink-soft">Regime-aware insight cards with confidence, data quality, and a suggested research action. Research only.</p>
        </div>
        <StressInsightGrid cards={stressInsights} />
      </section>

      <MethodologyCallout
        items={[
          "Input metrics are deterministic factor payloads: SMA200 breadth, 20-day momentum, annualized 20-day volatility, RSI, and provider metadata.",
          "Template memo appears when no LLM key is configured; LLM memo appears only when server-side DeepSeek generation succeeds.",
          "Numbers, source labels, and fallback flags come from the engine, not from generated prose.",
          "The memo is a research summary and is not investment advice.",
        ]}
      />

      <section className="grid grid-cols-1 gap-4 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="card p-5">
          <div className="flex flex-wrap items-center gap-2">
            <StatusBadge status={marketSummary.tone} />
            <span className="text-[12px] text-ink-muted">{marketSummary.dataNote}</span>
          </div>
          <p className="mt-3 text-[16px] leading-relaxed text-ink">{marketSummary.summary}</p>
          <p className="mt-2 text-[13px] text-ink-muted">{marketSummary.risk}</p>
          {marketSummary.highlights.length > 0 && (
            <ul className="mt-4 space-y-1.5">
              {marketSummary.highlights.map((highlight) => (
                <li key={highlight} className="text-[12.5px] leading-relaxed text-ink-muted before:mr-2 before:text-ink-soft before:content-['•']">{highlight}</li>
              ))}
            </ul>
          )}
        </div>
        <div className="card p-5">
          <div className="panel-title">Model Reasoning Summary</div>
          <p className="mt-3 text-[13px] leading-relaxed text-ink-muted">
            The market model combines SMA200 breadth, 20-day momentum, annualized volatility, and fallback/adjusted data checks to produce regime language for research workflow prioritization.
          </p>
          <div className="mt-4 flex flex-wrap gap-2">
            <StatusBadge status={marketSummary.source === "deepseek" ? "deepseek memo" : "template memo"} />
            <StatusBadge status="research only" />
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-4">
        <MarketInsightCard label="Above SMA200" value={`${above}/${factors.length}`} detail="Trend filter across the default watchlist." />
        <MarketInsightCard label="Average 20d return" value={pct(avgMom20)} detail="Calculated from 20-day close-to-close returns." />
        <MarketInsightCard label="Average 20d volatility" value={pctPlain(avgVol)} detail="Annualized from daily returns." />
        <MarketInsightCard label="Adjusted sources" value={`${metadata.adjustedCount}/${metadata.symbolCount}`} detail="Corporate-action-adjusted price series used when available." />
      </section>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-5">
        {factors.map((factor) => (
          <div key={factor.symbol} className="card p-4">
            <div className="flex items-center justify-between">
              <div className="font-semibold text-ink">{factor.symbol}</div>
              <StatusBadge status={factor.aboveSma200 ? "trend ok" : "trend weak"} />
            </div>
            <div className="mt-3 space-y-1.5 text-[12px] text-ink-muted">
              <div className="flex justify-between"><span>Mom 20d</span><span className="num text-ink">{factor.momentum20d === null ? "n/a" : pct(factor.momentum20d)}</span></div>
              <div className="flex justify-between"><span>Vol 20d</span><span className="num text-ink">{factor.volatility20d === null ? "n/a" : pctPlain(factor.volatility20d)}</span></div>
              <div className="flex justify-between"><span>RSI</span><span className="num text-ink">{factor.rsi14 === null ? "n/a" : num(factor.rsi14, 1)}</span></div>
            </div>
          </div>
        ))}
      </section>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">
        {derivedNotes.map(([title, detail]) => (
          <div key={title} className="card p-4">
            <div className="text-[10px] uppercase tracking-[0.18em] text-ink-soft">Data-Derived Note</div>
            <h2 className="mt-2 text-[15px] font-semibold text-white">{title}</h2>
            <p className="mt-2 text-[12.5px] leading-relaxed text-ink-muted">{detail}</p>
          </div>
        ))}
      </section>
    </div>
  );
}
