import MarketInsightCard from "@/components/cards/MarketInsightCard";
import StatusBadge from "@/components/badges/StatusBadge";
import { getResearchDataset } from "@/lib/research";
import { pct, pctPlain, num } from "@/lib/utils/format";

export const revalidate = 60 * 60;

export default async function AIMarketPage() {
  const { factors, marketSummary, metadata } = await getResearchDataset();
  const above = factors.filter((factor) => factor.aboveSma200).length;
  const avgMom20 = factors.reduce((sum, factor) => sum + (factor.momentum20d ?? 0), 0) / Math.max(factors.length, 1);
  const avgVol = factors.reduce((sum, factor) => sum + (factor.volatility20d ?? 0), 0) / Math.max(factors.length, 1);

  return (
    <div className="space-y-8">
      <header>
        <div className="section-label">L4 AI Market</div>
        <h1 className="mt-2 text-[32px] font-semibold tracking-tight text-ink">AI Market Intelligence</h1>
        <p className="mt-2 max-w-3xl text-[14px] leading-relaxed text-ink-muted">
          AI-written tape note layered on top of deterministic factor breadth, volatility, and trend metrics. When DEEPSEEK_API_KEY is set, the prose is generated by DeepSeek; otherwise it falls back to the template.
        </p>
      </header>

      <section className="grid grid-cols-1 gap-4 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="card p-5">
          <div className="flex flex-wrap items-center gap-2">
            <StatusBadge status={marketSummary.tone} />
            <span className="text-[12px] text-ink-muted">{marketSummary.dataNote}</span>
          </div>
          <p className="mt-3 text-[16px] leading-relaxed text-ink">{marketSummary.summary}</p>
          <p className="mt-2 text-[13px] text-ink-muted">{marketSummary.risk}</p>
          {marketSummary.highlights.length > 0 && (
            <ul className="mt-4 space-y-1.5">
              {marketSummary.highlights.map((highlight) => (
                <li key={highlight} className="text-[12.5px] leading-relaxed text-ink-muted before:mr-2 before:text-ink-soft before:content-['•']">{highlight}</li>
              ))}
            </ul>
          )}
        </div>
        <div className="card p-5">
          <div className="panel-title">Model Reasoning Summary</div>
          <p className="mt-3 text-[13px] leading-relaxed text-ink-muted">
            The market model combines SMA200 breadth, 20-day momentum, annualized volatility, and fallback/adjusted data checks to produce regime language for research workflow prioritization.
          </p>
          <div className="mt-4 flex flex-wrap gap-2">
            <StatusBadge status={marketSummary.source === "deepseek" ? "deepseek memo" : "template memo"} />
            <StatusBadge status="research only" />
          </div>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-4">
        <MarketInsightCard label="Above SMA200" value={`${above}/${factors.length}`} detail="Trend filter across the default watchlist." />
        <MarketInsightCard label="Average 20d return" value={pct(avgMom20)} detail="Calculated from 20-day close-to-close returns." />
        <MarketInsightCard label="Average 20d volatility" value={pctPlain(avgVol)} detail="Annualized from daily returns." />
        <MarketInsightCard label="Adjusted sources" value={`${metadata.adjustedCount}/${metadata.symbolCount}`} detail="Corporate-action-adjusted price series used when available." />
      </section>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-5">
        {factors.map((factor) => (
          <div key={factor.symbol} className="card p-4">
            <div className="flex items-center justify-between">
              <div className="font-semibold text-ink">{factor.symbol}</div>
              <StatusBadge status={factor.aboveSma200 ? "trend ok" : "trend weak"} />
            </div>
            <div className="mt-3 space-y-1.5 text-[12px] text-ink-muted">
              <div className="flex justify-between"><span>Mom 20d</span><span className="num text-ink">{factor.momentum20d === null ? "n/a" : pct(factor.momentum20d)}</span></div>
              <div className="flex justify-between"><span>Vol 20d</span><span className="num text-ink">{factor.volatility20d === null ? "n/a" : pctPlain(factor.volatility20d)}</span></div>
              <div className="flex justify-between"><span>RSI</span><span className="num text-ink">{factor.rsi14 === null ? "n/a" : num(factor.rsi14, 1)}</span></div>
            </div>
          </div>
        ))}
      </section>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">
        {[
          ["Growth momentum", "Strengthening across mega-cap technology leadership."],
          ["Quality crowding", "Elevated versus recent baseline; monitor factor concentration."],
          ["Volatility regime", "Low-volatility conditions favor defensive trend-following setups."],
          ["Sector breadth", "Improving in semiconductors and automation proxies."],
        ].map(([title, detail]) => (
          <div key={title} className="card p-4">
            <div className="text-[10px] uppercase tracking-[0.18em] text-ink-soft">AI Research Note</div>
            <h2 className="mt-2 text-[15px] font-semibold text-white">{title}</h2>
            <p className="mt-2 text-[12.5px] leading-relaxed text-ink-muted">{detail}</p>
          </div>
        ))}
      </section>
    </div>
  );
}
