import Link from "next/link";
import { ArrowRight, FileText } from "lucide-react";
import type { HotspotTheme } from "@/lib/agents/types";
import ProxyBasket from "./ProxyBasket";
import ScenarioTable from "./ScenarioTable";

const ASSET_LABEL: Record<HotspotTheme["assetType"], string> = {
  "private-market-catalyst": "Private-market catalyst",
  "public-proxy": "Public proxy basket",
  "macro-rotation": "Macro rotation",
};

/**
 * Hotspot Research Brief — a report-style write-up of a single theme for the
 * Reports page. Template-generated from the deterministic catalyst engine.
 */
export default function HotspotResearchBrief({ theme }: { theme: HotspotTheme }) {
  const isPrivate = theme.assetType === "private-market-catalyst";
  const briefName = `${theme.title.split(" / ")[0]} Catalyst Brief`;

  return (
    <section className="card relative overflow-hidden p-6 panel-glow">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <div className="grid h-9 w-9 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-300/[0.07]">
            <FileText className="h-5 w-5 text-cyan-200" />
          </div>
          <div>
            <div className="section-label">Hotspot Research Brief</div>
            <h2 className="mt-0.5 text-[18px] font-semibold tracking-tight text-white">{briefName}</h2>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className={`chip ${isPrivate ? "border-amber-300/35 bg-amber-400/10 text-amber-100" : "border-cyan-300/30 bg-cyan-400/[0.08] text-cyan-100"}`}>
            {ASSET_LABEL[theme.assetType]}
          </span>
          <span className="text-[10.5px] font-medium uppercase tracking-[0.14em] text-ink-soft">Template memo</span>
        </div>
      </div>

      <div className="mt-5 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div className="space-y-5">
          <Block title="Catalyst summary">
            <p className="text-[13px] leading-relaxed text-ink">{theme.catalystSummary}</p>
            {isPrivate && theme.assetTypeNote && (
              <p className="mt-2 text-[12px] leading-relaxed text-amber-100/90">{theme.assetTypeNote}</p>
            )}
          </Block>
          <Block title="Proxy basket">
            <ProxyBasket proxies={theme.proxies} coverage={theme.dataCoverage} title="Public-market proxies" />
          </Block>
          <Block title="Strategy relevance">
            {theme.strategyRelevance.length > 0 ? (
              <div className="space-y-1.5">
                {theme.strategyRelevance.map((s) => (
                  <Link key={s.strategyId} href={`/strategies/${s.strategyId}`} className="block rounded-xl border border-line bg-white/[0.025] p-2.5 text-[12px] text-ink-muted transition-colors hover:border-cyan-300/30 hover:text-ink">
                    <span className="font-medium text-white">{s.strategyName}</span> — {s.note}
                  </Link>
                ))}
              </div>
            ) : (
              <p className="text-[12px] leading-relaxed text-ink-soft">No in-universe radar strategy currently maps to this theme&rsquo;s proxy basket.</p>
            )}
          </Block>
        </div>

        <div className="space-y-5">
          <Block title="Scenario forecast">
            <ScenarioTable scenario={theme.scenario} basketLabel={`${theme.title} proxy basket`} />
          </Block>
          <Block title="Risk flags">
            <ul className="space-y-1.5">
              {theme.riskFlags.map((flag) => (
                <li key={flag} className="flex items-start gap-2 text-[12px] leading-relaxed text-ink-muted">
                  <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-rose-300/70" />
                  {flag}
                </li>
              ))}
            </ul>
          </Block>
        </div>
      </div>

      <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4">
        <p className="max-w-3xl text-[11.5px] leading-relaxed text-ink-soft">
          <span className="font-medium text-ink-muted">Research disclaimer. </span>
          Generated by the demo catalyst engine from configured templates and market data — no live news feed. Scenario
          ranges are estimates for the public-market proxy basket, not investment advice or a price prediction.
        </p>
        <Link href="/hotspots" className="inline-flex shrink-0 items-center gap-1 text-[12px] font-medium text-cyan-200/90 transition-colors hover:text-cyan-100">
          Open Market Hotspots <ArrowRight className="h-3.5 w-3.5" />
        </Link>
      </div>
    </section>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="section-label">{title}</div>
      <div className="mt-2">{children}</div>
    </div>
  );
}
